language: python
python: "3.7"

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
env:
  global:
    - TEST_DIR=/tmp/test_dir/
    - MODULE=strlearn
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.7" COVERAGE="true"
      NUMPY_VERSION="1.14.1" SCIPY_VERSION="1.0.0" CYTHON_VERSION="0.23.4"

install: source ci_scripts/travis/install.sh
script: bash ci_scripts/travis/test.sh
after_success: source ci_scripts/travis/success.sh


notifications:
  email: true
